"""add feature_flags table

Revision ID: 3c1cf4c7a4b5
Revises: c16b77a3df9d
Create Date: 2026-05-13 21:59:40.001802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1cf4c7a4b5'
down_revision: Union[str, Sequence[str], None] = 'c16b77a3df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    if_not_exists=True,
)
    # Remove old test table if exists (was part of auto-generated migration)
    op.execute("DROP TABLE IF EXISTS test")
    op.drop_index(op.f('ix_source_group_members_group_id'), table_name='source_group_members')
    op.drop_index(op.f('idx_schedules_is_enabled'), table_name='source_group_schedules')
    op.drop_index(op.f('uq_sources_name_active'), table_name='sources', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('uq_sources_url_active'), table_name='sources', sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.create_index(op.f('uq_sources_url_active'), 'sources', ['url'], unique=1, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_sources_name_active'), 'sources', ['name'], unique=1, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_schedules_is_enabled'), 'source_group_schedules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_source_group_members_group_id'), 'source_group_members', ['group_id'], unique=False)
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.drop_table('feature_flags')
    # ### end Alembic commands ###