# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

project_root = Path(SPECPATH).parent

a = Analysis(
    ['../src/main_stdio.py'],
    pathex=[str(project_root)],
    binaries=[],
    datas=[
        ('../alembic', 'alembic'),
        ('../alembic.ini', '.'),
        ('../src', 'src'),
    ],
    hiddenimports=[
        'src',
        'src.stdio',
        'src.stdio.server',
        'src.stdio.router',
        'src.stdio.protocol',
        'src.api',
        'src.api.deps',
        'src.api.routes',
        'src.api.routes.feed',
        'src.api.routes.health',
        'src.api.routes.keys',
        'src.api.routes.logs',
        'src.api.routes.sources',
        'src.api.routes.stats',
        'src.db',
        'src.db.database',
        'src.models',
        'src.models.base',
        'src.models.feed_item',
        'src.models.source',
        'src.models.api_key',
        'src.models.stats',
        'src.models.fetch_log',
        'src.formatters',
        'src.formatters.base',
        'src.formatters.json_formatter',
        'src.formatters.rss_formatter',
        'src.formatters.md_formatter',
        'src.scheduler',
        'src.scheduler.fetch_scheduler',
        'src.utils',
        'src.utils.time',
        'src.config',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'alembic',
        'alembic.config',
        'alembic.command',
        'alembic.migration',
        'alembic.script',
        'alembic.runtime.migration',
        'greenlet',
        'httpx',
        'feedparser',
        'pydantic_settings',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='rss-sidecar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)